import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');
const isSmallDevice = width < 375;
const isMediumDevice = width >= 375 && width < 414;
const isLargeDevice = width >= 414;

// Tamanhos responsivos
const getResponsiveSize = {
  title: isSmallDevice ? 24 : isMediumDevice ? 26 : 28,
  subtitle: isSmallDevice ? 12 : isMediumDevice ? 14 : 16,
  buttonText: isSmallDevice ? 16 : isMediumDevice ? 18 : 20,
  buttonPaddingVertical: isSmallDevice ? 10 : 12,
  buttonPaddingHorizontal: isSmallDevice ? 30 : 40,
  letterSpacing: isSmallDevice ? 4 : 6,
};

export const CyberpunkStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000',
    overflow: 'hidden',
    paddingHorizontal: 20,
  },
  titleContainer: {
    alignItems: 'center',
    zIndex: 10,
    marginTop: height * 0.35,
    maxWidth: '90%',
  },
  title: {
    fontFamily: 'Cyberpunk',
    fontSize: getResponsiveSize.title,
    color: '#fcee09',
    textShadowColor: '#000',
    textShadowOffset: { width: -1, height: -1 },
    textShadowRadius: 1,
    marginBottom: 5,
    textAlign: 'center',
    includeFontPadding: false,
  },
  titleShadow: {
    fontFamily: 'Cyberpunk',
    fontSize: getResponsiveSize.title,
    color: 'transparent',
    textShadowColor: '#fcee09',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 15,
    opacity: 0.7,
    position: 'absolute',
    textAlign: 'center',
    includeFontPadding: false,
  },
  subtitle: {
    fontFamily: 'Cyberpunk',
    fontSize: getResponsiveSize.subtitle,
    color: 'rgba(252, 238, 9, 0.6)',
    letterSpacing: getResponsiveSize.letterSpacing,
    textTransform: 'uppercase',
    marginTop: 10,
    textAlign: 'center',
    includeFontPadding: false,
  },
  button: {
    paddingVertical: getResponsiveSize.buttonPaddingVertical,
    paddingHorizontal: getResponsiveSize.buttonPaddingHorizontal,
    backgroundColor: '#fcee09',
    borderWidth: 2,
    borderColor: '#000',
    borderRadius: 8,
    zIndex: 15,
    shadowColor: '#fcee09',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 8,
    elevation: 5,
    minWidth: 150,
    alignSelf: 'center',
  },
  buttonContainer: {
    position: 'absolute',
    bottom: height * 0.15,
    zIndex: 10,
  },
  buttonPressed: {
    transform: [{ scale: 0.95 }],
    shadowColor: '#000',
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 3,
  },
  buttonHover: {
    backgroundColor: '#000',
    borderColor: '#fcee09',
    shadowColor: '#fcee09',
  },
  buttonText: {
    fontFamily: 'Cyberpunk',
    color: '#000',
    fontSize: getResponsiveSize.buttonText,
    textTransform: 'uppercase',
    letterSpacing: 1,
    textAlign: 'center',
    includeFontPadding: false,
  },
  buttonTextHover: {
    color: '#fcee09',
  },
  scanlines: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'transparent',
    opacity: 0.03,
    zIndex: 1,
  },
  fullGlitch: {
    backgroundColor: '#000',
    opacity: 0.8,
    ...StyleSheet.absoluteFillObject,
    zIndex: 999,
  },
  particle: {
    position: 'absolute',
    borderRadius: 50,
  },
  contentWrapper: {
    flex: 1,
    width: '100%',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingVertical: 40,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.95)',
    zIndex: 1000,
  },
  modalContent: {
    width: '90%',
    backgroundColor: '#000',
    borderWidth: 3,
    borderColor: '#fcee09',
    padding: 20,
    alignItems: 'center',
    shadowColor: '#fcee09',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 10,
    elevation: 10,
    borderRadius: 15, // Mais arredondado
  },
  modalTitle: {
    fontFamily: 'Cyberpunk',
    fontSize: getResponsiveSize.title - 4,
    color: '#fcee09',
    textShadowColor: '#000',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 8,
    marginBottom: 20,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  input: {
    width: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    borderColor: '#fcee09',
    borderWidth: 2,
    color: '#fcee09',
    padding: 12,
    marginVertical: 10,
    fontSize: getResponsiveSize.buttonText - 2,
    textAlign: 'center',
    zIndex: 15,
    shadowColor: '#fcee09',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    borderRadius: 8, // Arredondado
  },
  switchText: {
    color: '#fcee09',
    marginTop: 15,
    fontFamily: 'Cyberpunk',
    fontSize: getResponsiveSize.subtitle,
    textTransform: 'uppercase',
    textAlign: 'center',
    zIndex: 15,
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  modalParticle: {
    position: 'absolute',
    borderRadius: 50,
    backgroundColor: '#fcee09',
    opacity: 0.2, // Menos visível
  },
});